name = "SyntheticLGE"
uuid = "8bb4aab0-0619-4fe5-8de9-681bab176a63"
authors = ["Calder Sheagren <caldersheagren@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"

[compat]
DICOM = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
